[package]
name = "coil-lang"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[workspace]
members = ["coil-error", "coil-parser", "coil-lexer"]

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
coil-lexer = { path = "coil-lexer" }
