[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "rlib", "dylib", "staticlib"]

[dependencies]
coil-error = { path = "../coil-error" }
phf = { version = "0.11.2", features = ["macros"] }
